// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// squarify
NumericMatrix squarify(const NumericMatrix& mask, const NumericVector& D_mask);
RcppExport SEXP _acreworkshop_squarify(SEXP maskSEXP, SEXP D_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type D_mask(D_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(squarify(mask, D_mask));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_acreworkshop_squarify", (DL_FUNC) &_acreworkshop_squarify, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_acreworkshop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
